import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
// import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";


// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        {/* <Header/> */}
        {children}
        {/* <Footer/> */}
        </body>
    </html>
  );
}
